description = "git commit & git push origin main"
prompt = """
* "{{args}}"が"minor"だった場合は、package.jsonのバージョンを「0.1.0」上げる
* "{{args}}"が"patch"だった場合は、package.jsonのバージョンを「0.0.1」上げる
* このコマンドが実行された時点までの作業をコミットする
* バージョン番号のtagを付ける
* 作業ブランチがmainでなかった場合はmainにmergeする
* mainにmergeした後に、GitHubにmainブランチをpushする
* 新しいバージョンで付けたtagもpushする
"""

